# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "512ea10fd2150c887cec1de609c54976"
name = "AnnouncePlus"
application_url = "https://announceplus.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
dev_store_url = "makerbase-teststore.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_metaobjects,read_metaobjects"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://announceplus.fly.dev/auth/callback",
  "https://announceplus.fly.dev/auth/shopify/callback",
  "https://announceplus.fly.dev/api/auth/callback"
]
